[workspace]
members = [
  "crates/client/db",
  "crates/client/exec",
  "crates/client/sync",
  "crates/client/eth",
  "crates/client/rpc",
  "crates/client/telemetry",
  "crates/client/metrics",
  "crates/client/mempool",
  "crates/client/block_import",
  "crates/node",
  "crates/primitives/block",
  "crates/primitives/convert",
  "crates/primitives/transactions",
  "crates/primitives/class",
  "crates/primitives/receipt",
  "crates/primitives/state_update",
  "crates/primitives/chain_config",
  "crates/primitives/utils",
  "crates/primitives/validation",
  "crates/tests",
]
resolver = "2"
default-members = [
  "crates/client/db",
  "crates/client/exec",
  "crates/client/sync",
  "crates/client/eth",
  "crates/client/rpc",
  "crates/client/telemetry",
  "crates/client/metrics",
  "crates/client/mempool",
  "crates/client/block_import",
  "crates/node",
  "crates/primitives/block",
  "crates/primitives/convert",
  "crates/primitives/transactions",
  "crates/primitives/class",
  "crates/primitives/receipt",
  "crates/primitives/state_update",
  "crates/primitives/chain_config",
  "crates/primitives/utils",
  "crates/primitives/validation",
  "crates/tests",
]

[profile.dev]
incremental = true
panic = "abort"

[profile.release]
panic = "unwind"

[profile.production]
codegen-units = 1    # Setting this to 1 allows for more optimizations at the cost of slower compile time
inherits = "release"
lto = "fat"          # Enables Link Time Optimization, enabling more aggressive optimizations across the entire codebase
opt-level = 3        # Optimize for speed regardless of binary size or compile time
rpath = false        # Disables adding rpath to the binary
strip = "symbols"    # Removes debug info and symbold from final binary

[workspace.package]
authors = ["KasarLabs <https://github.com/KasarLabs>"]
homepage = "https://kasar.io"
edition = "2021"
repository = "https://github.com/KasarLabs/deoxys/"
version = "0.1.0"
license = "Apache-2.0"

[workspace.dependencies]
rocksdb = { version = "0.22", features = [
  # "multi-threaded-cf",
] }

# Bonsai trie dependencies
bonsai-trie = { default-features = false, git = "https://github.com/cchudant/bonsai-trie.git", branch = "fix_inserts_remove_leaks", features = [
  "std",
] }

# Deoxys primtitives
dp-block = { path = "crates/primitives/block", default-features = false }
dp-convert = { path = "crates/primitives/convert", default-features = false }
dp-transactions = { path = "crates/primitives/transactions", default-features = false }
dp-class = { path = "crates/primitives/class", default-features = false }
dp-receipt = { path = "crates/primitives/receipt", default-features = false }
dp-state-update = { path = "crates/primitives/state_update", default-features = false }
dp-utils = { path = "crates/primitives/utils", default-features = false }
dp-chain-config = { path = "crates/primitives/chain_config", default-features = false }
dp-validation = { path = "crates/primitives/validation", default-features = false }

# Deoxys client
dc-telemetry = { path = "crates/client/telemetry" }
dc-db = { path = "crates/client/db" }
dc-exec = { path = "crates/client/exec" }
dc-rpc = { path = "crates/client/rpc" }
dc-sync = { path = "crates/client/sync" }
dc-eth = { path = "crates/client/eth" }
dc-metrics = { path = "crates/client/metrics" }
dc-mempool = { path = "crates/client/mempool" }
dc-block-import = { path = "crates/client/block_import" }

# Starknet dependencies
cairo-vm = "=1.0.0-rc5"
starknet-core = "0.11"
starknet-crypto = "0.7"
starknet-providers = "0.11"

starknet-types-core = { version = "0.1.5", default-features = false, features = [
  "hash",
] }

blockifier = "=0.8.0-rc.0"
starknet_api = "=0.13.0-rc.0"
cairo-lang-starknet-classes = "=2.7.0-rc.2"
cairo-lang-utils = "=2.7.0-rc.2"

alloy = { version = "0.2.0", features = [
  "node-bindings",
  "rpc-types",
  "provider-http",
  "contract",
] }

# Other third party dependencies
anyhow = "1.0"
assert_matches = "1.5"
async-trait = "0.1"
sha3 = "0.10"
bitvec = { version = "1.0", default-features = false, features = ["std"] }
clap = { version = "4.4" }
flate2 = "1.0"
futures = { version = "0.3", default-features = false, features = ["std"] }
jsonrpsee = { version = "0.22", default-features = false, features = [
  "server",
] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4", features = ["cors"] }
governor = "0.6"
hyper = { version = "0.14", features = ["server"] }
ip_network = "0.4"
lazy_static = { version = "1.4", default-features = false }
once_cell = "1.19"
log = { version = "0.4", features = ["std", "kv_std"] }
num-traits = "0.2"
num-bigint = "0.4"
primitive-types = "0.12"
rand = "0.8"
reqwest = { version = "0.12", features = ["json"] }
rstest = "0.18"
serde = { version = "1.0", default-features = false, features = ["std"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
thiserror = "1.0"
tokio = { version = "1.34", features = ["signal"] }
url = "2.4"
rayon = "1.10"
bincode = "1.3"
prometheus = "0.13.4"
fdlimit = "0.3.0"
proptest = "1.5.0"
proptest-derive = "0.5.0"
dotenv = "0.15.0"
httpmock = "0.7.0"
tempfile = "3.10.1"
env_logger = "0.11.3"

[patch.crates-io]
starknet-core = { git = "https://github.com/kasarlabs/starknet-rs.git", branch = "fork" }
starknet-providers = { git = "https://github.com/kasarlabs/starknet-rs.git", branch = "fork" }

# wait for PR https://github.com/starknet-io/types-rs/pull/76 to be merged
starknet-types-core = { git = "https://github.com/kasarlabs/types-rs.git", branch = "feat-deserialize-v0.1.5" }

blockifier = { git = "https://github.com/starkware-libs/blockifier", tag = "v0.8.0-rc.0" }
