[workspace]
members = [
  "crates/client/db",
  "crates/client/exec",
  "crates/client/sync",
  "crates/client/rpc",
  "crates/client/telemetry",
  "crates/client/metrics",
  "crates/node",
  "crates/primitives/block",
  "crates/primitives/convert",
  "crates/primitives/transactions",
  "crates/primitives/class",
  "crates/primitives/receipt",
  "crates/primitives/state_update",
  "crates/primitives/utils",
]
resolver = "2"
# All previous except for `starknet-rpc-test` and `starknet-e2e-test`
# We don't want `cargo test` to trigger its tests
default-members = [
  "crates/client/db",
  "crates/client/exec",
  "crates/client/sync",
  "crates/client/rpc",
  "crates/client/telemetry",
  "crates/client/metrics",
  "crates/node",
  "crates/primitives/block",
  "crates/primitives/transactions",
  "crates/primitives/class",
  "crates/primitives/receipt",
  "crates/primitives/state_update",
  "crates/primitives/utils",
]

[profile.dev]
incremental = true
panic = "abort"

[profile.release]
panic = "unwind"

[profile.production]
codegen-units = 1    # Setting this to 1 allows for more optimizations at the cost of slower compile time
inherits = "release"
lto = "fat"          # Enables Link Time Optimization, enabling more aggressive optimizations across the entire codebase
opt-level = 3        # Optimize for speed regardless of binary size or compile time
rpath = false        # Disables adding rpath to the binary
strip = "symbols"    # Removes debug info and symbold from final binary

[workspace.package]
authors = ["KasarLabs <https://github.com/KasarLabs>"]
homepage = "https://kasar.io"
edition = "2021"
repository = "https://github.com/KasarLabs/deoxys/"
version = "0.1.0"
license = "Apache-2.0"

[workspace.dependencies]
rocksdb = { version = "0.22", features = [
  # "multi-threaded-cf",
] }

# Bonsai trie dependencies
bonsai-trie = { default-features = false, git = "https://github.com/cchudant/bonsai-trie.git", branch = "fix_inserts_remove_leaks", features = [
  "std",
] }

# Deoxys primtitives
dp-block = { path = "crates/primitives/block", default-features = false }
dp-convert = { path = "crates/primitives/convert", default-features = false }
dp-transactions = { path = "crates/primitives/transactions", default-features = false }
dp-class = { path = "crates/primitives/class", default-features = false }
dp-receipt = { path = "crates/primitives/receipt", default-features = false }
dp-state-update = { path = "crates/primitives/state_update", default-features = false }
dp-utils = { path = "crates/primitives/utils", default-features = false }

# Deoxys client
dc-telemetry = { path = "crates/client/telemetry" }
dc-db = { path = "crates/client/db" }
dc-exec = { path = "crates/client/exec" }
dc-rpc = { path = "crates/client/rpc" }
dc-sync = { path = "crates/client/sync" }
dc-metrics = { path = "crates/client/metrics" }

# Starknet dependencies
cairo-vm = "=0.9.2"
starknet-core = "0.11"
starknet-crypto = "0.7"
starknet-providers = "0.11"

starknet-types-core = { version = "0.1", default-features = false, features = [
  "hash",
] }

blockifier = "=0.6.0-rc.2"
starknet_api = "=0.10.0"
cairo-lang-starknet-classes = "2.6.0"
cairo-lang-utils = "2.6.0"

# Ethers: using the same versions as in Anvil
ethers = { git = "https://github.com/gakonst/ethers-rs" }

# Other third party dependencies
anyhow = "1.0"
assert_matches = "1.5"
async-trait = "0.1"
sha3 = "0.10"
bitvec = { version = "1.0", default-features = false, features = ["std"] }
base64 = "0.13"
clap = { version = "4.4" }
derive_more = { version = "0.99", default-features = false }
flate2 = "1.0"
futures = { version = "0.3", default-features = false, features = ["std"] }
hex = { version = "0.4", default-features = false, features = ["std"] }
indexmap = { version = "2.2", features = ["std", "rayon", "serde"] }
itertools = "0.12"
jsonrpsee = { version = "0.22", default-features = false, features = [
  "server",
] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4", features = ["cors"] }
governor = "0.6"
hyper = { version = "0.14", features = ["server"] }
ip_network = "0.4"
lazy_static = { version = "1.4", default-features = false }
once_cell = "1.19"
log = { version = "0.4", features = ["std", "kv_std"] }
num-traits = "0.2"
num-bigint = "0.4"
primitive-types = "0.12"
rand = "0.8"
reqwest = { version = "0.12", features = ["json"] }
rstest = "0.18"
serde = { version = "1.0", default-features = false, features = ["std"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
serde_with = { version = "2.3", default-features = false }
thiserror = "1.0"
thiserror-no-std = "2.0"
tokio = "1.34"
url = "2.4"
rayon = "1.10"
crossbeam-skiplist = "0.1"
bincode = "1.3"
prometheus = "0.13.4"
fdlimit = "0.3.0"
tempfile = "3.10.1"

[patch.crates-io]
starknet-core = { git = "https://github.com/kasarlabs/starknet-rs.git", branch = "fork" }
starknet-providers = { git = "https://github.com/kasarlabs/starknet-rs.git", branch = "fork" }

# wait for PR https://github.com/starknet-io/types-rs/pull/76 to be merged
starknet-types-core = { git = "https://github.com/jbcaron/types-rs.git", rev = "fd0e062" }
