[package]
name = "dc-mempool"
description = "Deoxys client mempool service"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]

proptest.workspace = true
proptest-derive.workspace = true
bitvec.workspace = true
env_logger.workspace = true

blockifier = { workspace = true, features = ["testing"] }

[dependencies]

# Deoxys
dc-block-import.workspace = true
dc-db.workspace = true
dc-exec.workspace = true
dp-block.workspace = true
dp-chain-config.workspace = true
dp-class.workspace = true
dp-convert.workspace = true
dp-receipt.workspace = true
dp-state-update.workspace = true
dp-transactions.workspace = true
dp-utils.workspace = true
dp-validation.workspace = true

# Starknet
blockifier.workspace = true
starknet-types-core.workspace = true
starknet_api.workspace = true

# Other
anyhow.workspace = true
async-trait.workspace = true
hyper.workspace = true
log.workspace = true
rayon.workspace = true
thiserror.workspace = true
tokio.workspace = true
