[package]
description = "Madara Execution Extensions"
name = "mp-exex"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
homepage.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
mc-block-import = { workspace = true }
mp-block.workspace = true
mp-chain-config = { workspace = true }
mp-rpc = { workspace = true }

# Other
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
log.workspace = true
rayon.workspace = true
rstest = { workspace = true }
serde.workspace = true
starknet_api.workspace = true
tokio = { workspace = true, features = ["signal"] }
tokio-stream.workspace = true
tokio-util.workspace = true
