environments:
  - project: devnet
    id: 5ac2bbca-b3e1-4849-b04c-116819c6c13a
    repos:
      madara:
        image: apoorvsadana/madara:85fb08e3cfec70a47999c4b2909ff1e4536040ad
        config:
          --network: "devnet"
          --chain-config-path: "./pragma-devnet.yaml"
          --devnet: ""
